### ISSUE TITLE
Is there a way to tell if plugin is active without logging in to WP? 

### ISSUE THREAD

**Issue by jmelick** [broadly/wordpress-plugin#8]
What about a test page that produces plugin details, something like <sitedomain.com>/broadly-wordpress-status --> where this page will return results about plugin? Other namespace issues around using a URL scheme like that?

**Comment by ericthelefty** [comment]
Would be helpful for troubleshooting to fetch WP version. Per @jmelick  - also fetch host data, other plugins, etc.
